### ISSUE TITLE
Give team members access to necessary resources (GitHub etc.)

### ISSUE THREAD

**Issue by blakecooper** [5-MuhSkuhTeers/StudyApp#16]
1) Add your PM to the GitHub repo (GitHub username: blakecooper, email: blakecoo@buffalo.edu) 
2) Make certain each team member can use the repo. This starts with adding each teammate as a contributor (or admin) in the repo. Also, verify each teammate can pull (download) and push (upload) to the repo. Create an "authors.txt" file with your name in it. Each teammate will then pull down the repo, add their name to the file, and push that change back. (This can happen in the main branch, since it is part of setup.) 
3) (For web app projects) Create the space on [heroku.com] and make certain all teammates can read and write to it.

**Comment by MikeLeishear** [comment]
1) Blake was given read and write access to the github repository as an outside collaborator.
2) Each member of the group has read and write access to the repository.  This has been confirmed by having each member one at a time pull a file, "authors.txt", add their name to it, and then push it back to the repo.  This file can be seen on the repo.
3) A heroku space has been created for the project.  It has been shared with everyone in the group, now including Blake.  It has no real deployable features, but everyone can see, access, and edit the space.
