### ISSUE TITLE
Begin building UI prototype in Figma

### ISSUE THREAD

**Issue by blakecooper** [5-MuhSkuhTeers/StudyApp#17]
Set up a project in Figma and build a prototype that includes: (1) your app's initial screen (login, level selector, or similar), (2) the main screen or 1st level which follows that initial page, and (3) any pages where important data will be shown. 

Please make notes in this ZenHub task as you go, so your teammates (and the PM) can confirm your work. These notes should include: 
1) The link created by the "Share" button to the Figma page containing the prototype 
2) Links to any website(s) you used if you needed help getting this work completed in Figma

**Comment by alejandraLuGa** [comment]
**Link to UI prototype:**
     https://www.figma.com/file/FcAUrnDW4xDOx17eBEIYIW/study-app?node-id=7%3A80
**Websites and references:**
- https://www.instagram.com/accounts/emailsignup/
- [https://app.zenhub.com/files/402905678/87f1d7dd-e6fe-4d6d-a253-0d960b0ef9e0/download](https://app.zenhub.com/files/402905678/87f1d7dd-e6fe-4d6d-a253-0d960b0ef9e0/download)
