### ISSUE TITLE
Identify tools needed for data storage

### ISSUE THREAD

**Issue by blakecooper** [5-MuhSkuhTeers/StudyApp#18]
Please research and make notes in this ZenHub task as you go, so your teammates (and the PM) can confirm your work. These notes should include: 

1) Your chosen database technology for this project (SQL etc.) 
2) Links to website(s) containing documentation and how-tos for how to use this technology 
3) Links to website(s) showing how to create the database/tables/structures in this technology 
4) Simple program that reads and writes to that storage approach 
5) (For web projects) links to website(s) showing how to get the language working in a Docker container

**Comment by conan-sum** [comment]
Webpages:
https://dev.mysql.com/doc/refman/8.0/en/linux-installation-docker.html
https://hub.docker.com/r/mysql/mysql-server/

**Comment by conan-sum** [comment]
Task test
1. Refer to the comment and confirm that it contains the information requested
