### ISSUE TITLE
Identify languages and libraries needed for back-end programming

### ISSUE THREAD

**Issue by blakecooper** [5-MuhSkuhTeers/StudyApp#19]
Please research and make notes in this ZenHub task as you go, so your teammates (and the PM) can confirm your work. These notes should include: 

1) A list of language(s) and libraries you plan on using for this project 
2) Links to website(s) containing documentation and how-tos for all of the language and libraries 
3) "Hello world" written in your project's main language AND another program that results in the display of a simple window or webpage (can push to GitHub on a dev branch) 
4) (For web projects) links to website(s) showing how to get the language working in a Docker container 
5) A brief explanation of why you will not need any other languages or libraries to get the work done.

**Comment by zemingzhang1** [comment]
1) A list of language(s) and libraries you plan on using for this project.
Frontend: Typescript, html, CSS
Server: Flask, MySQL, Python, Postgresql (maybe)
Backend: Python
Libraries: JSON, Bootstrap3

2) Links to website(s) containing documentation and how-tos for all of the language and libraries.
Typescript:
       - Basics/ how tos: https://www.youtube.com/watch?v=ahCwqrYpIuM 
       - Documentation: https://devdocs.io/typescript/
       - source code: https://github.com/microsoft/TypeScript.git
Python:
       - Basics/ how tos: https://realpython.com/lessons/write-simple-server/
       - Documentation: https://docs.python.org/3/
       - Py3 : https://www.python.org/downloads/release/python-390/
HTML:
       - Basics/ how tos: https://www.youtube.com/watch?v=UB1O30fR-EE 
       - Documentation: https://www.w3schools.com/html/html_intro.asp
       - source code: https://html.com/resources/free-html-templates/
CSS:
       - Basics/ how tos: https://www.w3schools.com/css/
       - Documentation: https://devdocs.io/css/
       - source code: https://www.w3schools.com/w3css/w3css_templates.asp
Flask:
       - Basics/ how tos: https://www.youtube.com/watch?v=ahCwqrYpIuM 
       - Documentation: https://flask.palletsprojects.com/en/2.0.x/
       - source code: https://github.com/berlotto/flask-app-template/tree/master/app/templates
       - Templates: https://code.visualstudio.com/docs/python/tutorial-flask
MySQL:
       - Basics/ how tos: https://dev.mysql.com/doc/workbench/en/dbdoc-templates-custom.html
       - Documentation: https://www.mysql.com/
       - templates: https://www.sqlshack.com/visual-studio-code-for-mysql-and-mariadb-development/
PostgreSQL:
       - How tos: https://www.postgresql.org/
       - Documentation: https://www.postgresql.org/docs/current/
Libs:
       - JSON: https://www.json.org/json-en.html
       - Bootstrap3: https://getbootstrap.com/; https://devdocs.io/bootstrap~3/


3) "Hello world" written in your project's main language AND another program that results in the display of a simple window or webpage (can push to GitHub on a dev branch).
Will present in class
4) (For web projects) links to website(s) showing how to get the language working in a Docker container.
Docker images: https://docs.docker.com/language/python/build-images/
Docker containment: https://www.docker.com/blog/containerized-python-development-part-1/

5) A brief explanation of why you will not need any other languages or libraries to get the work done.
The Listed libraries and tools are sufficient for a full stack development. The tools used for front end will be html for the page framework, CSS and bootstrap will be used to articulate the html framework and to embed designs, typescript will be used in replace of javascript for the functionalities of the web page and query calls. The back end will compose of Flask which is in python for server development along with JSON for query post and get request. To store user data we will use MySQL and PostgreSQL which is a structured database. The tools mentioned in the project structure description above explains all necessary tools needed to implement a full stack web app, in which no additional tools are necessary.
